Feature/update court
Engenharia-de-software-Gp05/Backend-Complexo-Esportivo-UFCG pull request #85
Opened 2024-03-29 02:14 UTC by lucaslimasilvafoligem

2024-03-30 14:28 UTC, samuelcluna reviewed
pedi algumas alterações

2024-03-30 14:28 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +        return new ResponseEntity<>(response, HttpStatus.CREATED);
HttpStatus.OK

2024-03-30 14:28 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +            CourtSaveDto data,
Acredito que seja melhor ter um dto especifico pra update

2024-03-30 14:28 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtServiceImpl.java
> +        Court court = repository.findById(id).orElseThrow(SaceResourceNotFoundException::new);
trocar repository.findById por this.findById. E colocar a mensagem de erro adequada usando a classe de constantes

2024-03-30 22:19 UTC, samuelcluna requested changes

2024-03-30 22:19 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtServiceImpl.java
> +        Court court = this.findById(id).orElseThrow(() -> notFoundException(id));
deixa o erro explicito, esse método privado pra lançar exceção não tá bacana

2024-03-30 22:19 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtServiceImpl.java
> +    private SaceResourceNotFoundException notFoundException(Long id) {
não deveria existir

2024-03-30 22:19 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/dto/court/CourtUpdateDto.java
> +        @NotBlank(message = "name cannot be empty")
se for colocar mensagem nas validações precisa seguir o padrão pra todos os dtos, acho que não é necessário

2024-03-31 12:56 UTC, samuelcluna commented
Resolver conflitos

2024-03-31 22:53 UTC, samuelcluna requested changes
Pequenas alterações

2024-03-31 22:53 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +    public ResponseEntity<Void> delete(
trocar por deleteById

2024-03-31 22:53 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +    @DeleteMapping(value = "/delete")
trocar path pra /delete/by/id

2024-03-31 22:53 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtService.java
> +    void delete(Long id);
trocar pra deleteById

2024-03-31 22:53 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtServiceImpl.java
> +        repository.delete(court);
usar o service, this.deleteById(id). Recomendo revisar os  métodos que são implementados pelo BasicService

2024-03-31 22:53 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtServiceImpl.java
> +        Court court = repository.findById(id).orElseThrow(() -> new SaceResourceNotFoundException(
usar o exists pra verificar se existe e se não lançar exceção

2024-03-31 23:05 UTC, samuelcluna requested changes
Recomendo fazer um teste de unidade pro método update principalmente um teste pro service. Acredito que atualizar uma estrutura de dados dessa forma não funciona( Me refiro a image urls ser uma lista e você apenas setar uma nova lista, se bem me lembro não funciona)

2024-03-31 23:05 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +    @PutMapping("/update")
trocar pra /update/by/id

2024-03-31 23:05 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +    public ResponseEntity<CourtResponseDto> update(
updateById

2024-03-31 23:05 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +        CourtResponseDto response = service.update(data, id);
updateById

2024-03-31 23:05 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtService.java
> +    CourtResponseDto update(CourtUpdateDto data, Long id);
updateById

2024-03-31 23:06 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +                    description = "Successfully update court",
updated*

2024-03-31 23:06 UTC, samuelcluna commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/controller/CourtController.java
> +                    description = "Failed update court",
updated*

2024-04-01 01:04 UTC, lucaslimasilvafoligem commented on src/main/java/com/ufcg/es5/BackendComplexoEsportivoUFCG/application/court/service/CourtServiceImpl.java
> +        Court court = repository.findById(id).orElseThrow(() -> new SaceResourceNotFoundException(
O findById por padrão já pede pra lançar a exceção, eu só estou disponibilizando ele com a mensagem adequada, botar exists é redudante, porque no fim ele vai usar o findbyId

2024-04-02 00:39 UTC, samuelcluna requested changes
Trocar as chamadas de métodos do repository para métodos do próprio service quando já foram implementadas. Usar os métodos de exists pra verificar ocorrencia dos dados invés de usar métodos de find. Considerar criar um método privado checkIfExistsById(Long id) que chama o método existsById(do service) numa condicional e lança a exceção com a mensagem correta caso o retorno seja false if(!existsById(id))

2024-04-04 20:53 UTC, samuelcluna approved these changes

2024-04-04 20:53 UTC, merged